<?php

/**
 * @file
 * Views Tree module.
 */

/**
 * Implements hook_views_api().
 */
function views_tree_views_api() {
  return array(
    'api' => '3',
    'path' => backdrop_get_path('module', 'views_tree'),
  );
}

/**
 * Implements hook_autoload_info().
 */
function views_tree_autoload_info() {
  return array(
    'views_tree_plugin_style_tree' => 'views_tree_plugin_style_tree.inc',
  );
}

/**
 * Implements hook_theme().
 */
function views_tree_theme($existing, $type, $theme, $path) {
  return array(
    'views_view_tree' => array(
      'variables' => array(
        'view' => NULL,
        'options' => array(),
        'rows' => array(),
        'title' => NULL,
      ),
      'file' => 'views_tree.theme.inc',
      'path' => backdrop_get_path('module', 'views_tree'),
    ),
    'views_tree_inner' => array(
      'variables' => array(
        'view' => NULL,
        'options' => array(),
        'rows' => array(),
        'title' => NULL,
        'result' => array(),
        'parent' => NULL,
      ),
      'file' => 'views_tree.theme.inc',
      'path' => backdrop_get_path('module', 'views_tree'),
    ),
  );
}
